# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.CharField(max_length=50)),
                ('current_location', models.CharField(max_length=50)),
                ('sender_name', models.CharField(max_length=50)),
                ('sender_address', models.CharField(max_length=50)),
                ('sender_city', models.CharField(max_length=50)),
                ('sender_country', models.CharField(max_length=50)),
                ('sender_zip', models.CharField(max_length=50)),
                ('sender_contact', models.CharField(max_length=50)),
                ('receiver_name', models.CharField(max_length=50)),
                ('receiver_address', models.CharField(max_length=50)),
                ('receiver_city', models.CharField(max_length=50)),
                ('receiver_country', models.CharField(max_length=50)),
                ('receiver_zip', models.CharField(max_length=50)),
                ('receiver_contact', models.CharField(max_length=50)),
            ],
        ),
    ]
