# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0002_auto_20160520_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
