# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0004_auto_20160527_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
                ('phone_number', models.CharField(max_length=50, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('company_name', models.CharField(max_length=50, verbose_name='\u516c\u53f8\u540d')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='\u5730\u5740')),
                ('postcode', models.CharField(max_length=50, verbose_name='\u90ae\u653f\u7f16\u7801')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('order_id', models.CharField(max_length=10, verbose_name='\u8ba2\u5355\u53f7')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='\u65f6\u95f4')),
                ('status', models.CharField(max_length=50, verbose_name='\u72b6\u6001')),
                ('location', models.CharField(max_length=50, verbose_name='\u5f53\u524d\u4f4d\u7f6e')),
                ('primKey', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingUser',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
                ('phone_number', models.CharField(max_length=50, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('company_name', models.CharField(max_length=50, verbose_name='\u516c\u53f8\u540d')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='\u5730\u5740')),
                ('postcode', models.CharField(max_length=50, verbose_name='\u90ae\u653f\u7f16\u7801')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receiver_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receiver_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receiver_contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receiver_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receiver_zip',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sender_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sender_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sender_contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sender_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sender_zip',
        ),
        migrations.RemoveField(
            model_name='order',
            name='update_time',
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_id',
            field=models.CharField(max_length=10, null=True, verbose_name='\u6536\u4ef6\u4eba'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_id',
            field=models.CharField(max_length=10, null=True, verbose_name='\u53d1\u4ef6\u4eba'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_user_id',
            field=models.CharField(max_length=10, null=True, verbose_name='\u627f\u8fd0\u4eba'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='\u91cd\u91cf'),
        ),
    ]
