# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0006_order_shiping_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_user_id',
        ),
    ]
