# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0007_remove_order_shipping_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shiping_user_email',
            new_name='shipping_user_email',
        ),
    ]
