# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0008_auto_20160623_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_user_email',
            new_name='shipping_user_id',
        ),
    ]
